# Generated by Django 2.2a1 on 2021-06-18 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_mail', models.EmailField(max_length=70, unique=True)),
                ('user_phone', models.CharField(max_length=100)),
                ('user_password', models.CharField(default='ABCD', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default='Title Unavailable', max_length=255)),
                ('blog_desc', models.CharField(default='Description Unavailable', max_length=255)),
                ('blog_created_at', models.DateField()),
                ('blog_img', models.ImageField(default='', upload_to='blog/')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blogapp.Users')),
            ],
        ),
    ]
