# Generated by Django 2.2a1 on 2021-06-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='user_id',
            new_name='user',
        ),
    ]
