# Generated by Django 2.2a1 on 2021-06-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_password',
            field=models.CharField(default='ABCD', max_length=200),
        ),
    ]
