# Generated by Django 2.2a1 on 2021-06-17 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_users_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_mail',
            field=models.EmailField(max_length=70, unique=True),
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default='Title Unavailable', max_length=255)),
                ('blog_desc', models.CharField(default='Description Unavailable', max_length=255)),
                ('blog_created_at', models.DateField()),
                ('blog_img', models.ImageField(default='', upload_to='blog/')),
                ('use_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blogapp.Users')),
            ],
        ),
    ]
