# Generated by Django 2.2a1 on 2021-06-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210618_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_img',
            field=models.FileField(default='', upload_to='blog/'),
        ),
    ]
